[package]
name = "diflouroborane"
version = "0.1.0"
authors = ["Gregor Reitzenstein <me@dequbed.space>"]
license = "GPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: reduce the feature groups for faster compilation
#tokio = { version = "0.2", features = ["full"] }

futures = { version = "0.3", features = ["thread-pool", "compat"] }
futures-util = "0.3"
futures-signals = "0.3"

smol = "1.0"

signal-hook = { version = "0.1", features = ["tokio-support"] }

slog = { version = "2.5", features = ["max_level_trace"] }
slog-term = "2.6"
slog-async = "2.5"

capnp = "0.13"
capnp-rpc = "0.13"
capnp-futures = "0.13"

toml = "0.5"
serde = { version = "1.0", features = ["derive"] }

uuid = { version = "0.8", features = ["serde", "v4"] }

clap = "2.33"

rsasl = "0.1"

[build-dependencies]
capnpc = "0.13"
