[package]
name = "diflouroborane"
version = "0.1.0"
authors = ["Gregor Reitzenstein <me@dequbed.space>"]
license = "GPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["lmdb"]

# Use LMDB for internal kv-stores
lmdb = []

[dependencies]
futures = { version = "0.3", features = ["thread-pool", "compat"] }
futures-util = "0.3"
futures-signals = "0.3"

smol = "1.0"

signal-hook = "0.1"

slog = { version = "2.5", features = ["max_level_trace"] }
slog-term = "2.6"
slog-async = "2.5"

capnp = "0.13"
capnp-rpc = "0.13"
capnp-futures = "0.13"

serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
flexbuffers = "0.1"

serde_dhall = { version =  "0.9", default-features = false }

uuid = { version = "0.8", features = ["serde", "v4"] }

clap = "2.33"

# TODO update this if bindgen breaks (again)
rsasl = "0.2.3"
#rsasl = { path = "../../rsasl" }

# rumqtt needs tokio which I'm trying to get away from
paho-mqtt = { git = "https://github.com/dequbed/paho.mqtt.rust.git", branch = "master", features = ["build_bindgen"] }

#mlua = { version = "0.4", features = ["async", "luajit"] }

libc = "0.2"
lmdb-rkv = "0.14"

async-trait = "0.1"

lazy_static = "1.4.0"

rust-argon2 = "0.8"
rand = "0.7"

async-channel = "1.5"
easy-parallel = "3.1"
genawaiter = "0.99"

[build-dependencies]
capnpc = "0.13"

[dev-dependencies]
futures-test = "0.3"
