[package]
name = "diflouroborane"
version = "0.3.0"
authors = [ "dequbed <me@dequbed.space>"
          , "Kai Jan Kriegel <kai@kjkriegel.de>"
          , "Joseph Langosch <thejoklla@gmail.com>"
          , "Jannis Rieger <omniskopus@gmail.com>"
          ]
license = "LGPL-3.0"
edition = "2018"

[profile.dev]
lto = "thin"

[profile.release]
opt-level = 3
debug = true
lto = "thin"

[dependencies]
libc = "0.2.101"
lazy_static = "1.4.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
async-trait = "0.1.51"

# Runtime
bastion = "0.4"
nuclei = { version = "0.1.3" }

# Catch&Handle POSIX process signals
signal-hook = "0.3.9"

# Argument parsing for bin/bffhd.rs
clap = "2.33.3"

# Internal Databases
lmdb-rkv = "0.14.0"
rkyv = "0.7"
ptr_meta = "0.1"
rkyv_typename = "0.7"
rkyv_dyn = "0.7"
inventory = "0.1"

# Password hashing for internal users
rust-argon2 = "0.8.3"
rand = "0.8.4"

# Async aware logging and tracing
tracing = "0.1.28"
tracing-subscriber = "0.2.25"

# API
capnp = "0.14.3"
capnpc = "0.14.4"
capnp-rpc = "0.14.1"
capnp-futures = "0.14.1"

# API Authentication
rsasl = "1.4.0" # TODO update this if bindgen breaks (again)
#rsasl = { path = "../../rsasl" }

futures-signals = "0.3.22"
async-oneshot = "0.5"

smol = "1.2.5"

# Config and Database (De)Serialization
serde = { version = "1.0.130", features = ["derive"] }
erased-serde = "0.3"
serde_dhall = { version = "0.10.1", default-features = false }
serde_json = "1.0"

# Shelly support
paho-mqtt = { git = "https://github.com/dequbed/paho.mqtt.rust.git", branch = "master", features = ["build_bindgen"] }

[build-dependencies]
capnpc = "0.14.4"
# Used in build.rs to iterate over all files in schema/
walkdir = "2.3.2"

[dev-dependencies]
futures-test = "0.3.16"
tempfile = "3.2"
bincode = "1.3"