// @generated by the capnpc-rust plugin to the Cap'n Proto schema compiler.
// DO NOT EDIT.
// source: programming_language/csharp.capnp


#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum TypeVisibility {
  Public = 0,
  Internal = 1,
}
impl ::capnp::traits::FromU16 for TypeVisibility {
  #[inline]
  fn from_u16(value: u16) -> ::core::result::Result<TypeVisibility, ::capnp::NotInSchema> {
    match value {
      0 => ::core::result::Result::Ok(TypeVisibility::Public),
      1 => ::core::result::Result::Ok(TypeVisibility::Internal),
      n => ::core::result::Result::Err(::capnp::NotInSchema(n)),
    }
  }
}
impl ::capnp::traits::ToU16 for TypeVisibility {
  #[inline]
  fn to_u16(self) -> u16 { self as u16 }
}
impl ::capnp::traits::HasTypeId for TypeVisibility {
  #[inline]
  fn type_id() -> u64 { 0xeb0d_8316_68c6_eda5u64 }
}
